name: dart_discord_rpc_ffi
description: Internal dependency package for dart_discord_rpc.
repository: https://github.com/alexmercerind/dart_discord_rpc
homepage: https://github.com/alexmercerind/dart_discord_rpc
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
