name: dart_discord_rpc_ffi
description: Internal dependency package for dart_discord_rpc.
repository: https://github.com/alexmercerind/dart_discord_rpc
homepage: https://github.com/alexmercerind/dart_discord_rpc
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^1.1.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  ffigen: ^3.0.0

ffigen:
  output: "lib/generated/bindings.dart"
  dart-bool: true
  headers:
    entry-points:
      - "headers/**.h"
  name: "DiscordClient"
  description: "Dart bindings to Discord Game SDK client."
  llvm-path:
    - /usr/lib/llvm-13
  comments:
    style: any
    length: full
  sort: true
  preamble: "// ignore_for_file: camel_case_types, non_constant_identifier_names"
  globals:
    rename:
      # Removes '_' from
      # beginning of a name.
      "_(.*)": "$1"
