name: dart_discord_rpc
description: Discord Rich Presence for Flutter & Dart apps & games.
version: 0.0.1
repository: https://github.com/RPMTW/dart_discord_rpc
homepage: https://github.com/RPMTW/dart_discord_rpc
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dart_discord_rpc_ffi:
    git: 
      url: https://github.com/RPMTW/dart_discord_rpc.git
      path: ffi
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DartDiscordRpcPlugin
      windows:
        pluginClass: DartDiscordRpcPlugin
      macos:
        pluginClass: DartDiscordRpcPlugin
