name: dart_discord_rpc
description: Discord Rich Presence for Flutter & Dart apps & games.
version: 0.0.1
repository: https://github.com/alexmercerind/dart_discord_rpc
homepage: https://github.com/alexmercerind/dart_discord_rpc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dart_discord_rpc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc
      path: ffi
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  dart_discord_rpc_ffi:
    path: ffi

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DartDiscordRpcPlugin
      windows:
        pluginClass: DartDiscordRpcPlugin
      macos:
        pluginClass: DartDiscordRpcPlugin
